Repository jqassistant-tooling/intellij-jqassistant-plugin, pull requests merged in 2024-11, with the labels that each got.

#14 Editor: Add yaml config schema provider
  gradle.properties
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/config/ConfigFileUtils.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/config/YamlConfigSchemaProvider.kt
  src/main/resources/META-INF/plugin.xml
  src/main/resources/schemata/config.schema.json
Labels: muss

#29 Editor: Add xml schema provider
  build.gradle.kts
  gradle/libs.versions.toml
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/common/NanoXmlUtil.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/rules/XmlRuleSchemaProvider.kt
  src/main/resources/META-INF/plugin.xml
Labels: muss

#31 Editor: Register jqassistant for the spellchecker
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/spellchecker/JqaBundledDictionaryProvider.kt
  src/main/resources/META-INF/plugin.xml
  src/main/resources/org/jqassistant/tooling/intellij/plugin/editor/spellchecker/jqassistant.dic
Labels: muss

#30 Editor: Add report provider and tool window factory
  build.gradle.kts
  gradle.properties
  gradle/libs.versions.toml
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/data/ReportProviderService.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/report/ReportCellRenderer.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/report/ReportNode.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/report/ReportToolWindowContent.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/report/ReportToolWindowFactory.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/jqa/.gitkeep
  src/main/resources/META-INF/plugin.xml
Labels: report visualisation, muss

#32 Data: Add rule indexing interfaces and xml index
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/common/Extensions.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/data/rules/JqaRuleDefinition.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/data/rules/JqaRuleIndexingService.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/data/rules/JqaRuleIndexingStrategy.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/data/rules/xml/Dom.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/data/rules/xml/JqaXmlRuleIndexingStrategy.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/data/rules/xml/NameIndex.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/rules/RuleReference.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/rules/XmlRuleReferenceContributor.kt
  src/main/resources/META-INF/plugin.xml
Labels: rule-managment, muss, psi

#38 Docs: Mention EDT restrictions for indexing service
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/data/rules/JqaRuleIndexingService.kt
Labels: enhancement

#39 Data: Adjust xml rule index to point to attribute value instead of tag
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/data/rules/xml/JqaXmlRuleIndexingStrategy.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/data/rules/xml/NameIndex.kt
Labels: muss

#40 Misc: Add ktlint
  .editorconfig
  .github/workflows/build.yml
  .github/workflows/release.yml
  .github/workflows/style_checks.yml
  build.gradle.kts
  gradle/libs.versions.toml
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/common/NanoXmlUtil.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/data/rules/JqaRuleIndexingService.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/data/rules/JqaRuleIndexingStrategy.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/data/rules/xml/Dom.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/data/rules/xml/JqaXmlRuleIndexingStrategy.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/data/rules/xml/NameIndex.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/config/ConfigFileUtils.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/config/YamlConfigSchemaProvider.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/rules/RuleReference.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/rules/XmlRuleReferenceContributor.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/rules/XmlRuleSchemaProvider.kt
Labels: enhancement
