Repository jqassistant-tooling/intellij-jqassistant-plugin, pull requests merged in 2024-12, with the labels that each got.

#42 #17 feature/effective-config
  gradle/libs.versions.toml
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/data/config/CommandLineTool.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/data/config/EventListener.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/data/config/JqaConfigFileProvider.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/data/config/JqaConfigurationService.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/data/config/JqaEffectiveConfigProvider.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/config/toolwindow/EffectiveConfigToolBar.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/config/toolwindow/EffectiveConfigToolWindow.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/config/toolwindow/EffectiveConfigToolWindowFactory.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/config/toolwindow/LoadingPanel.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/config/toolwindow/OutdatedConfigBannerPanel.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/config/toolwindow/RefreshAction.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/config/toolwindow/TextScrollPane.kt
  src/main/resources/META-INF/plugin.xml
  src/main/resources/icons/jqaShortIcon.svg
  src/main/resources/icons/jqaShortIcon_mono.svg
Labels: kann

#54 Data+Editor: Add jQA plugins to external libs view
  build.gradle.kts
  gradle/libs.versions.toml
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/data/plugin/JqaPluginRootsProvider.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/data/plugin/JqaPluginService.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/data/plugin/xml/Dom.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/plugin/SynchronizePlugins.kt
  src/main/resources/META-INF/plugin.xml
Labels: external plugins, muss

#57 CI: Use correct token variable for publishing
  .github/workflows/release.yml
Labels: kann, organisation

#60 Remove cache for plugin verifier step
  .github/workflows/build.yml
Labels: organisation

#55 #53 Add Editor with syntax highlighting (Read-only)
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/config/toolwindow/EffectiveConfigToolWindow.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/config/toolwindow/OutdatedConfigBannerPanel.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/config/toolwindow/TextScrollPane.kt
Labels: configuration, enhancement

#52 Editor: Report: Add speed search to table and reload button
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/report/GroupingNode.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/report/ReportCellRenderer.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/report/ReportToolWindowContent.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/report/ReportToolWindowFactory.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/report/actions/LayoutSwitchAction.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/report/actions/RefreshAction.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/report/actions/SearchAction.kt
Labels: report, muss, enhancement

#56 Editor: Report: Add inlay hints for report results
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/data/ReportProviderService.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/data/report/ReportProviderService.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/report/ReportToolWindowContent.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/report/ReportToolWindowFactory.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/report/inlay/ReportSingularRuleResultDeclarativeInlayHintsProvider.kt
  src/main/resources/META-INF/plugin.xml
  src/main/resources/messages/MyBundle.properties
Labels: report, psi

#61 Data+Editor: Use `PsiPolyVariantReference` and index rules with identical name in same rule file
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/data/rules/JqaRuleIndexingService.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/data/rules/JqaRuleIndexingStrategy.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/data/rules/xml/JqaXmlRuleIndexingStrategy.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/data/rules/xml/NameIndex.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/report/ReportToolWindowContent.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/rules/RuleReference.kt
Labels: muss, psi

#58 Feature/templates/rule.xml and jqa.yaml files template
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/templates/RuleJqaTemplateFileCreation.kt
  src/main/resources/META-INF/plugin.xml
  src/main/resources/icons/jqaIcon_16x16.svg
  src/main/resources/icons/jqaIcon_16x16_dark.svg
  src/test/kotlin/org/jqassistant/tooling/intellij/plugin/editor/templates/RuleJqaTemplateFileTest.kt
Labels: rule-managment, muss

#66 Disable gradle caches
  .github/workflows/build.yml
  .github/workflows/release.yml
  .github/workflows/run-ui-tests.yml
  .github/workflows/style_checks.yml
Labels: organisation

#68 Editor: Add initial config schema
  src/main/resources/schemata/config.schema.json
Labels: configuration, muss

#67 Fix possible out of bounds access and remove unimplemented search action
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/report/ReportToolWindowContent.kt
Labels: bug, report, muss

#77 Editor: Inject rule references through DOM
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/data/rules/xml/Dom.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/data/rules/xml/NameIndex.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/rules/XmlRuleReferenceContributor.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/rules/XmlRuleReferenceConverter.kt
  src/main/resources/META-INF/plugin.xml
Labels: muss, psi, enhancement

#78 Merge Release alpha.2
  gradle.properties
Labels: organisation

#76 Rule Safe Delete Refactoring #13 [MK10]
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/rules/refactoring/delete/RuleFileSafeDeleteProcessorDelegate.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/rules/refactoring/delete/RuleRefactoringSupportProvider.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/rules/refactoring/delete/RuleSafeDeleteProcessorDelegate.kt
  src/main/resources/META-INF/plugin.xml
Labels: rule-managment, muss

#82 Release: Alpha 3
  gradle.properties
Labels: organisation
