Repository jqassistant-tooling/intellij-jqassistant-plugin, pull requests merged in 2025-01, with the labels that each got.

#89 Data: Index plugin rules
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/common/Extensions.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/common/JaxbUtil.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/common/PluginUtil.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/data/plugin/JqaPluginRootsProvider.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/data/plugin/JqaPluginService.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/data/plugin/xml/Dom.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/data/rules/xml/JqaXmlRuleIndexingStrategy.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/data/rules/xml/NameIndex.kt
  src/main/resources/META-INF/plugin.xml
Labels: rule-managment, external plugins, muss, kann

#83 Report auto refresh
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/common/JQAssistantPluginDisposable.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/data/report/ReportProviderService.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/report/OutdatedReportBanner.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/report/ReportToolWindowContent.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/report/ReportToolWindowFactory.kt
Labels: report, enhancement

#90 Add report sorting and filtering
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/report/ReportNode.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/report/ReportToolWindowContent.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/report/actions/FilterAction.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/report/actions/SearchAction.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/report/actions/SortingToggleAction.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/report/tree/GroupingNode.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/report/tree/ReportCellRenderer.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/report/tree/ReportNode.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/report/tree/ReportTreeModel.kt
Labels: report, muss, enhancement

#91 Release Alpha 4
  gradle.properties
Labels: organisation

#94 Data: Add configuration service interface
  build.gradle.kts
  gradle.properties
  gradle/libs.versions.toml
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/common/PluginUtil.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/data/config/JqaConfigFactory.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/data/config/JqaConfigurationService.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/data/config/MavenConfigFactory.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/data/plugin/JqaPluginService.kt
  src/main/resources/META-INF/jqassistant-maven.xml
  src/main/resources/META-INF/plugin.xml
Labels: configuration

#95 Bump supported version range to 2025.1 (EAP)
  gradle.properties
Labels: organisation

#93 Feature: Resolve references in test api
  gradle.properties
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/rules/RuleReference.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/rules/UastReferenceContributor.kt
  src/main/resources/META-INF/jqassistant-uastReferenceContributor.xml
  src/main/resources/META-INF/plugin.xml
Labels: rule-managment, kann, psi, abgabe

#96 Release Alpha 5
  gradle.properties
Labels: organisation

#97 Data: Resolve wildcard rules
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/data/rules/xml/JqaXmlRuleIndexingStrategy.kt
Labels: rule-managment, psi, enhancement

#101 Misc: Merge ktlint workflow into build workflow
  .github/workflows/style_checks.yml
  build.gradle.kts
Labels: enhancement, organisation

#98 Data+Editor: Filter completion by type
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/data/rules/JqaRuleDefinition.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/data/rules/JqaRuleIndexingService.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/data/rules/JqaRuleIndexingStrategy.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/data/rules/xml/Dom.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/data/rules/xml/JqaXmlRuleIndexingStrategy.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/data/rules/xml/NameIndex.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/rules/RuleReference.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/rules/UastReferenceContributor.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/rules/XmlRuleReferenceConverter.kt
  src/main/resources/META-INF/plugin.xml
Labels: rule-managment, muss, psi

#104 Editor: Highlight cypher code in rule xml
  gradle.properties
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/data/rules/xml/Dom.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/rules/XmlRuleCypherEmbedding.kt
  src/main/resources/META-INF/jqassistant-graphdb.xml
  src/main/resources/META-INF/plugin.xml
Labels: psi, enhancement

#110 Search for matching file names instead of only checking known path for report
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/data/report/ReportProviderService.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/report/ReportToolWindowFactory.kt
Labels: report, enhancement

#102 Editor: Warn about usage of wildcard characters in `id`
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/MessageBundle.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/rules/XmlRuleDomInspection.kt
  src/main/resources/META-INF/plugin.xml
  src/main/resources/inspectionDescriptions/XmlRuleDom.html
  src/main/resources/messages/MyBundle.properties
Labels: psi, enhancement

#103 Editor: Add rule references to yaml config files
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/config/YamlConfigAnnotator.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/config/YamlConfigReferenceContributor.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/rules/RuleReference.kt
  src/main/resources/META-INF/plugin.xml
  src/main/resources/messages/MyBundle.properties
Labels: psi, enhancement

#111 Release Alpha 6
  gradle.properties
Labels: organisation

#105 Add settings UI
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/settings/PluginSettings.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/settings/PluginSettingsComponent.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/settings/PluginSettingsConfigurable.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/settings/ValidatorTextFieldWithBrowseButton.kt
  src/main/resources/META-INF/plugin.xml
Labels: configuration, enhancement

#113 Data: Implement JqaConfigurationService
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/common/Extensions.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/data/config/CliConfigFactory.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/data/config/JqaConfigFactory.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/data/config/JqaConfigurationService.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/data/config/MavenConfigFactory.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/data/plugin/JqaPluginService.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/config/SynchronizeConfig.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/settings/PluginSettings.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/settings/PluginSettingsComponent.kt
  src/main/resources/META-INF/plugin.xml
  src/main/resources/messages/MyBundle.properties
Labels: configuration, muss

#117 Config: Add project startup activity
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/data/config/AutoSyncConfigProjectActivity.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/data/plugin/JqaPluginService.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/plugin/SynchronizePlugins.kt
  src/main/resources/META-INF/plugin.xml
  src/main/resources/messages/MyBundle.properties
Labels: rule-managment, enhancement

#118 Misc: Use maven by default
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/settings/PluginSettings.kt
Labels: organisation

#125 Remove unused files and directories
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/data/config/CommandLineTool.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/data/config/EventListener.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/data/config/JqaConfigFileProvider.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/data/config/JqaConfigurationService.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/data/config/JqaEffectiveConfigProvider.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/config/toolwindow/LoadingPanel.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/editor/templates/JqaTemplateCreator.kt
  src/main/kotlin/org/jqassistant/tooling/intellij/plugin/jqa/.gitkeep
Labels: enhancement, abgabe

#122 Release alpha v7
  gradle.properties
Labels: organisation
